box: "ubuntu/trusty64"
# Box specifications
box_check_update : false
# Provider settings
provider: "virtualbox"
repositories:
  - "ppa:ondrej/php"
dependencies:
  - apache2
  - php5.6
  - postgre9.5-php5.6
  - xdebug-php5
copy:
  - etc/apt/sources.list.d/pgdg.list
  - etc/php/5.6/apache2/php.ini
  - usr/lib/php5/20131226/xdebug.so
#=================
# IP settings
ip_prefix: "1.1.0"
private_network_ips:
  - 100
# Synced folder
synced_folders:
  "./html" : "/var/www/html"
