box: "ubuntu/trusty64"
# Box specifications
boxCheckUpdate : false
# Provider settings
provider: "virtualbox"
providers:
  virtualbox:
    # Display the VirtualBox GUI when booting the machine
    gui: false
    # Customize the amount of memory on the VM:
    memory: 1024
repositories:
  - "ppa:ondrej/php"
dependencies:
  - apache2
  - php5.6
  - postgres9.5-php5.6
  - xdebug-php5
copy:
  - etc/apt/sources.list.d/pgdg.list
  - etc/php/5.6/apache2/php.ini
  - usr/lib/php5/20131226/xdebug.so
#=================
# IP settings
ipPrefix: "1.1.0"
ipPostfixes:
  - 100
# Synced folder
syncedFolders:
  "./html" : "/var/www/html"
