box: "ubuntu/trusty64"
# Box specifications
box_check_update : false
# Provider settings
provider: "virtualbox"
repositories:
  - "ppa:ondrej/php"
dependencies:
  - apache2
  - apache2-rewrite
  - php5.6
  - postgre9.5-php5.6
  - xdebug-php5.6
copy:
#=================
# IP settings
ip_prefix: "1.1.0"
private_network_ips:
  - 100
# Synced folder
synced_folders:
  "./html" : "/var/www/html"
